name : Posts Updater

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 11 */1 * *" # 매일 한국 시간 오후 8시에 1일마다 실행

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install feedparser
        pip3 install markdownify

    - name: Update posts
      run: |
        python3 posts-update-automation.py

    - name: Commit and push when there are changes
      run: |
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "jkl9087@naver.com"
          git config --local user.name "jectgenius"
          git commit -m "Update: posts via workflow-${{ github.run_number }}"
          git push
        fi